/******************************************
Treehouse FSJS Techdegree:
project 1 - A Random Quote Generator
******************************************/


// Call a function every 20000 milliseconds (OR 10 seconds).	
setInterval('printQuote()', 20000);

 
// Generates random background color
const randomValue = () => Math.floor(Math.random() *256);

function randomRGB(value) {
    const color = `rgb( ${value()},${value()},${value()} )`;
    return color;
}



/*** 
 * `quotes` array stors the properties of all of the quotes as objects

***/
const quotes = [
    {
       quote: 'Be the change that you wish to see in the world.',
       source: 'Mahatma Gandhi',
       citation:'',
       year:'',
       tags:'Insperation'
    },
    {
       quote: 'If you tell the truth, you do not have to remember anything.',
       source: 'Mark Twain',
       citation:'The Adventures of Tom Sawyer',
       year:'',
       tags:'Humor'
    },
    {
       quote: 'Always forgive your enemies; nothing annoys them so much.',
       source: 'Oscar Wilde',
       citation:'',
       year:'1876',
       tags:'Humor'
    },
    {
       quote: 'You miss 100 percent of the shots you never take',
       source: 'Wayne Gretzky',
       citation:'',
       year:'',
       tags:'Business'
    },
    {
       quote: 'Life is what happens when you’re busy making other plans.',
       source: 'John Lennon',
       citation:'Beautiful boy',
       year:'1980',
       tags:'Humor'
    }
    
];



/***
 * This function generates a random number not bigger then the amount of quotes in array above
 * It also assigns which quote will be returned based on the random number
***/

function getRandomQuote() {
   var randomNumber = Math.floor(Math.random() * quotes.length) + 0; 
   var randomQuote = quotes[randomNumber];
   return randomQuote

}



/***
 * This function picks up the random quote generated by "getRandomQuote()" builds html around it to properly display in the web browser.
 * It looks to see in the properties "citation" "Tags" and "year" exists and writes them to the html code if applicable 
 * It also calls the function to change background color
***/

function printQuote() {
   var quoteRandom = getRandomQuote();
   var html = `
   <p class="quote"> ${quoteRandom.quote} </p>
   <p class="source"> ${quoteRandom.source}
   `;

   if (`${quoteRandom.citation}`!=='') {
      html += `   <span class="citation"> ${quoteRandom.citation} </span>`;
    } 
    
    if (`${quoteRandom.year}`!=='') {
      html += `   <span class="year"> ${quoteRandom.year} </span>`;
    }

    if (`${quoteRandom.tags}`!=='') {
      html += `   <span class="tags"> ${quoteRandom.tags} </span>`;
    }

   html += `
   </p>     
   `;
   document.body.style.background = randomRGB(randomValue);
   return document.getElementById('quote-box').innerHTML = html;  
   
      
}



/***
 * click event listener for the print quote button
 * DO NOT CHANGE THE CODE BELOW!!
***/

document.getElementById('load-quote').addEventListener("click", printQuote, false);
